bioc_pkgs<-c(
  'batchelor',
  'Biobase',
  'BiocGenerics',
  'BiocStyle',
  'biomaRt',
  'DelayedArray',
  'DelayedMatrixStats',
  'DropletUtils',
  'edgeR',
  'EWCE',
  'GenomicRanges',
  'graph',
  'IRanges',
  'limma',
  'MAST',
  'multtest',
  'preprocessCore',
  'rhdf5',
  'S4Vectors',
  'scater',
  "MatrixGenerics",
  "DelayedArray",
  "ensembldb",
  "proBatch",
  "mixOmics",
  'basilisk',
  "ComplexHeatmap",
  "circlize",
  'fgsea',
  'org.Hs.eg.db',
  'clusterProfiler',
  'enrichplot',
  'edgeR',
  'AnnotationDbi',
  'WGCNA',
  'S4Vectors',
  'DESeq2',
  'EnsDb.Hsapiens.v86',
  'msigdbr',
  "SummarizedExperiment",
  'SingleCellExperiment',
  "MultiAssayExperiment",
  'rhdf5',
  'dplyr',
  'tidyr',
  'reshape2', 'pheatmap', 'corrplot',
  'ggplot2', 'ggbeeswarm', 'scales', 'GGally', 'doParallel', 'RColorBrewer',
  'cowplot', 'ggrepel', 'foreach', 'reticulate', 'HDF5Array', 'DelayedArray',
  'ggpubr', 'forcats', 'Rtsne', 'uwot',
  'systemfonts', 'ragg', 'Cairo', 'ggrastr', 'basilisk', 'mvtnorm','MOFA2',
  'EWCE','slingshot'
)


requireNamespace("BiocManager")
BiocManager::install(bioc_pkgs, ask=F)
