---
title: "Use case 2"
output: html_document
date: '2022-11-28'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Multi-omics signature of microglial activation case study

```{r}

table(metadata$diagnosis)
all_multiassay <- multiassay[,!is.na(multiassay$activated_microglia)]

Control_multiassay <- multiassay[, multiassay$diagnosis == "Control" & !is.na(multiassay$activated_microglia)]
Early_multiassay <- multiassay[, multiassay$diagnosis == "Mid" & !is.na(multiassay$activated_microglia)]
Late_multiassay <- multiassay[, multiassay$diagnosis == "Late" & !is.na(multiassay$activated_microglia)]
```

```{r}
all_multiassay=protein_DE_analysis(multiassay=all_multiassay,
                         slot="protein_processed",
                         dependent='metadata$mglia23_mf',
                         covariates=NA,
                         levels=NULL,
                         log2FoldChange = 0)



Late_multiassay=rna_DE_analysis(Late_multiassay,
                    dependent='activated_microglia',
                    levels=NA,
                    filter_protein_coding = TRUE,
                    log2FoldChange = 0.25)
```



```{r}


Control_multiassay=vertical_integration(Control_multiassay,
                                ID_type = "gene_name",
                                integration='sMBPLS',
                                dependent='activated_microglia',
                                design='avg',
                                ncomp=1,
                                list.keepX = list(mRNA = c(50), proteins = c(50))
                                )

Early_multiassay=vertical_integration(Early_multiassay,
                                ID_type = "gene_name",
                                integration='sMBPLS',
                                dependent='activated_microglia',
                                design='avg',
                                ncomp=1,
                                list.keepX = list(mRNA = c(100), proteins = c(100)))

Late_multiassay=vertical_integration(Late_multiassay,
                                ID_type = "gene_name",
                                integration='sMBPLS',
                                dependent='activated_microglia',
                                design='avg',
                                ncomp=1,
                                list.keepX = list(mRNA = c(50), proteins = c(50)))

Control_multiassay@metadata[["integration"]][["sMBPLS"]][["prop_expl_var"]]
Early_multiassay@metadata[["integration"]][["sMBPLS"]][["prop_expl_var"]]
Late_multiassay@metadata[["integration"]][["sMBPLS"]][["prop_expl_var"]]

all_multiassay=vertical_integration(all_multiassay,
                                ID_type = "gene_name",
                                integration='sMBPLS',
                                dependent='amyloid',
                                design='avg',
                                ncomp=2,
                                list.keepX = list(mRNA = c(200), proteins = c(200)))
```

```{r}

  signature_control <- extract_multiomic_signature(Control_multiassay,
    integration = "sMBPLS",
    component = 1
  )

  signature_early <- extract_multiomic_signature(Early_multiassay,
    integration = "sMBPLS",
    component = 1
  )

  signature_late <- extract_multiomic_signature(Late_multiassay,
    integration = "sMBPLS",
    component = 1
  )

  
    signature_all <- extract_multiomic_signature(all_multiassay,
    integration = "sMBPLS",
    component = 1
  )


```
```{r}
metadata$braak=ifelse(metadata$diagnosis=='Control','0-II',ifelse(metadata$diagnosis=='Mid','III-IV','V-VI'))

metadata$braak= factor(metadata$braak, levels = c("0-II","III-IV",'V-VI'))
ggboxplot(
  metadata,
  color='braak',
  x='braak',
  y="amyloid",
  ylab='% of activated microglia in midfrontal cortex',
  xlab='Stage',
  combine = FALSE,
  merge = FALSE)+
  scale_y_continuous(labels = scales::percent)+
  ggsignif::geom_signif(comparisons=list(c("0-II", "III-IV"), 
                                         c("III-IV", "V-VI"), 
                                         c("0-II", "V-VI")),
                        y_position=c(0.15,0.20,0.25)
  )

```

```{r}

list_signature_micro=list(control=c(  signature_control$detrimental$rna,  signature_control$detrimental$protein,signature_control$protective$rna,signature_control$protective$protein),
                    early=c(signature_early$detrimental$rna,signature_early$detrimental$protein,signature_early$protective$rna, signature_early$protective$protein),
                    late=c(signature_late$detrimental$rna,signature_late$detrimental$protein, signature_late$protective$rna,signature_late$protective$protein))



list_signature_micro=list(control=c(  signature_control$detrimental$rna,  signature_control$detrimental$protein),
                    early=c(signature_early$detrimental$rna,signature_early$detrimental$protein),
                    late=c(signature_late$detrimental$rna,signature_late$detrimental$protein))


list_signature_micro=list(control=c(  signature_control$protective$rna,  signature_control$protective$protein),
                    early=c(signature_early$protective$rna,signature_early$protective$protein),
                    late=c(signature_late$protective$rna,signature_late$protective$protein))

## rna only
list_signature_micro=list(control=c(  signature_control$detrimental$rna),
                    early=c(signature_early$detrimental$rna),
                    late=c(signature_late$detrimental$rna))

## protein
## rna only
list_signature_micro=list(control=c(  signature_control$detrimental$protein),
                    early=c(signature_early$detrimental$protein),
                    late=c(signature_late$detrimental$protein))


## all rna
list_signature_micro=list(control=c(  signature_control$detrimental$rna,  signature_control$protective$rna),
                    early=c(signature_early$detrimental$rna,signature_early$protective$rna),
                    late=c(signature_late$detrimental$rna, signature_late$protective$rna))

list_signature_micro=list(control=c(   signature_control$detrimental$protein,signature_control$protective$protein),
                    early=c(signature_early$detrimental$protein,signature_early$protective$protein),
                    late=c(signature_late$detrimental$protein, signature_late$protective$protein))


## all
list_signature_micro=c(signature_all$protective$rna,signature_all$protective$protein,signature_all$detrimental$rna,signature_all$detrimental$protein)


  list_signature_micro=lapply(list_signature_micro, function(x) {
    sub("*\\.[0-9]", "", x)})

  background <- .get_background(multiassay=multiassay, of = "full")

```

```{r}
max(Early_multiassay@metadata$integration$sMBPLS$loadings$mRNA)
max(Control_multiassay@metadata$integration$sMBPLS$loadings$mRNA)
max(Late_multiassay@metadata$integration$sMBPLS$loadings$mRNA)
max(all_multiassay@metadata$integration$sMBPLS$loadings$mRNA)
```


```{r}
metadata$diagnosis=factor(metadata$diagnosis, levels = c("Control", "Mid", "Late"))
metadata$activated_cortex=metadata$mglia23_it + metadata$mglia23_mf
metadata$total_cortex=metadata$mglia123_it + metadata$mglia123_mf
metadata$cortex_ratio=metadata$activated_cortex/metadata$total_cortex

ggboxplot(
  metadata,
  x='diagnosis',
  y="activated_microglia",
  combine = FALSE,
  merge = FALSE)+
  ggsignif::geom_signif(comparisons=list(c("Control", "Mid"), 
                    c("Mid", "Late"), 
                    c("Control", "Late")),
                    y_position=c(0.15,0.20,0.25)
                    )

ggboxplot(
  metadata,
  x='diagnosis',
  y="mglia123_it",
  combine = FALSE,
  merge = FALSE)+
  ggsignif::geom_signif(comparisons=list(c("Control", "Mid"), 
                    c("Mid", "Late"), 
                    c("Control", "Late")),
                    y_position=c(300,310,320)
                    )


ggboxplot(
  metadata,
  x='diagnosis',
  y="mglia23_it",
  combine = FALSE,
  merge = FALSE)+
  ggsignif::geom_signif(comparisons=list(c("Control", "Mid"), 
                    c("Mid", "Late"), 
                    c("Control", "Late")),
                    y_position=c(30,31,32)
                    )


ggboxplot(
  metadata,
  x='diagnosis',
  y="mglia23_mf",
  combine = FALSE,
  merge = FALSE)+
  ggsignif::geom_signif(comparisons=list(c("Control", "Mid"), 
                    c("Mid", "Late"), 
                    c("Control", "Late")),
                    y_position=c(30,31,32)
                    )



ggboxplot(
  metadata,
  x='diagnosis',
  y="mglia123_it",
  combine = FALSE,
  merge = FALSE)+
  ggsignif::geom_signif(comparisons=list(c("Control", "Mid"), 
                    c("Mid", "Late"), 
                    c("Control", "Late")),
                    y_position=c(30,31,32)
                    )

ggboxplot(
  metadata,
  x='diagnosis',
  y="mglia123_mf",
  combine = FALSE,
  merge = FALSE)+
  ggsignif::geom_signif(comparisons=list(c("Control", "Mid"), 
                    c("Mid", "Late"), 
                    c("Control", "Late")),
                    y_position=c(30,31,32)
                    )



ggboxplot(
  metadata,
  x='diagnosis',
  y="activated_cortex",
  combine = FALSE,
  merge = FALSE)+
  ggsignif::geom_signif(comparisons=list(c("Control", "Mid"), 
                    c("Mid", "Late"), 
                    c("Control", "Late")),
                    y_position=c(30,31,32)
                    )

ggboxplot(
  metadata,
  x='diagnosis',
  y="cortex_ratio",
  combine = FALSE,
  merge = FALSE)+
  ggsignif::geom_signif(comparisons=list(c("Control", "Mid"), 
                    c("Mid", "Late"), 
                    c("Control", "Late")),
                    y_position=c(0.05,0.07,0.1)
                    )


ggboxplot(
  metadata,
  x='diagnosis',
  y="amyloid",
  combine = FALSE,
  merge = FALSE)+
  ggsignif::geom_signif(comparisons=list(c("Control", "Mid"), 
                    c("Mid", "Late"), 
                    c("Control", "Late")),
                    y_position=c(20,23,25)
                    )


plot(metadata$amyloid,metadata$activated_microglia)
```


```{r}
ggplotRegression <- function (fit) {
  
  require(ggplot2)
  
  ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
    geom_point() +
    stat_smooth(method = "lm", col = "red") +
    labs(title = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                       "Intercept =",signif(fit$coef[[1]],5 ),
                       " Slope =",signif(fit$coef[[2]], 5),
                       " P =",signif(summary(fit)$coef[2,4], 5)))
}

fit1 <- lm(activated_microglia ~ amyloid, data = metadata)
ggplotRegression(fit1)

cor(metadata$activated_microglia,metadata$amyloid)

```


```{r}
man=data.frame(unlist(mancuso))
list_signature_micro_state<-lapply(list_signature_micro, function(x){ x[x %in% man$unlist.mancuso.]})

pathways <- clusterProfiler::compareCluster(
    geneCluster = list_signature_micro,
    fun = "enrichGO",
    OrgDb = "org.Hs.eg.db",
    keyType = "SYMBOL",
    universe = background,
    ont = "BP",
    minGSSize = 1,
    pAdjustMethod = "fdr",
    pvalueCutoff = 0.05,
    qvalueCutoff = 0.1
  )
```

```{r}
  xx <- pairwise_termsim(pathways)                     
  cnetplot(xx)
```

```{r}

library(qs)
mancuso=qread('/home/ems2817/RDS_ukdri/multiomics/multiomics/pipeline_17_05/ESA/microglial_activation/Mancuso_2022.qs')
selected=qread('/home/ems2817/RDS_ukdri/multiomics/Omix_test_env/selected_genesets.qs')


custom=list()
custom=lapply(list_signature_micro,function(x){enrichment_custom(genesets=mancuso,
                                                                 genes=x,
                                                                 reference=background)}
              )


  Important_GeneSets=flattenlist(Important_GeneSets)

    Important_GeneSets=Important_GeneSets[names(  Important_GeneSets) != "Astrocyte_signatures"] # without elements that are "b"

    Important_GeneSets=c(Important_GeneSets,mancuso)

custom=enrichment_custom(genesets=  mancuso,genes=list_signature_micro,reference=background)
dotplot(custom)

custom2=list()
custom2=lapply(list_signature_micro,function(x){enrichment_custom(genesets=selected,
                                                                 genes=x,
                                                                 reference=background)}
              )

pathways_d<- lapply(list_signature_micro, pathway_analysis_enrichr)
```

```{r}
AppendMe <- function(dfNames) {
  do.call(rbind, lapply(dfNames, function(x) {
    cbind(get(x), source = x)
  }))
}

control=custom$control
early= custom$early
late=custom$late
df=AppendMe(c('control','early','late'))
df$sig=ifelse(df$padj<=0.05,'*','ns')
df$braak=ifelse(df$source=='control','0-II',ifelse(df$source=='early','III-IV','V-VI'))

ggplot(df, aes(x=braak,y=TermID,fill=enrichment_ratio)) + geom_tile(aes(fill = enrichment_ratio),colour = "white") +
        geom_text(aes(label = sig), vjust = 1) + 
        theme_bw() +
        scale_fill_gradient2(name="Enrichment Ratio",midpoint=0.7,low = "white", high = "red") 
```

```{r}

df2=custom2$late
df2=df2[which(df2$padj<=0.05),]
ggplot(df2, aes(x=TermID,y=TermID,fill=enrichment_ratio)) + geom_tile(aes(fill = enrichment_ratio),colour = "white") +
        geom_text(aes(label = as.character(padj)), vjust = 1) + 
        theme_bw() +
        scale_fill_gradient2(name="Enrichment Ratio",midpoint=0.7,low = "white", high = "red") 
```


```{r}
custom$control
custom2$control
custom$early
custom$late
```
```{r}

in_early_late=intersect(list_signature_micro$early,list_signature_micro$late)
enrichment_custom(genesets=mancuso,genes=in_early_late,reference=background)

```

