#' Performs DE on multiomics object from the processed slots
#'
#' @param multiassay Multiassay experiment object generated by Omix
#' `generate_multiassay`function
#' @param dependent Dependent variable for the differential expression analysis,
#' usually the disease group variable
#' @param covariates Technical and biological covariates. Set as NULL is data
#' is denoised.
#' @param levels Character vector with reference group as first element.
#' @param log2FoldChange Log2FC absolute threshold. Default to 0.2
#'
#' @return List of differential expression results
#'
#' @family Single-omic
#'
#' @importFrom MultiAssayExperiment MultiAssayExperiment listToMap colData
#' getWithColData sampleMap
#' @importFrom SummarizedExperiment SummarizedExperiment
#' @importFrom stats as.formula
#' @importFrom magrittr set_names
#' @importFrom cli cli_alert_danger style_bold cli_alert_success
#' @importFrom limma makeContrasts lmFit contrasts.fit eBayes topTable
#'
#' @export
#'
DE_multiomics <- function(multiassay,
                          dependent = "diagnosis",
                          covariates = c("pmi", "msex", "age_death"),
                          levels = c("Control", "Mid", "Late"),
                          log2FoldChange = 0.2) {
  rna <- multiassay@metadata$multimodal_object$omics$mRNA
  protein <- multiassay@metadata$multimodal_object$omics$proteins
  colData <- multiassay@metadata$multimodal_object$metadata

  ####
  colData <- colData %>% mutate(across(where(is.character), as.factor))

  if (!is.null(covariates)) {
    cov_var <- paste(covariates, collapse = " + ")

    if (any(is.na(colData[covariates]))) {
      stop(cli::cli_alert_danger(
        paste("Missing value in covariates, please use other covariates")
      ))
    }
  } else {
    cov_var <- NA
  }

  dependent_var <- paste(dependent, collapse = " + ")

  if (!is.null(levels)) {
    colData[[dependent]] <- factor(colData[[dependent]], levels = levels)
  }

  for (i in colnames(colData)) {
    assign(i, colData[, i])
  }


  ### CATEGORICAL DEPENDENT
  if (!is.numeric(colData[, dependent])) {
    if (!is.na(cov_var)) {
      model_formula <- stats::as.formula(
        sprintf(
          "~0+ %s + %s",
          dependent_var,
          cov_var
        )
      )
    }
    if (is.na(cov_var)) {
      model_formula <- stats::as.formula(
        sprintf(
          "~0+ %s",
          dependent_var
        )
      )
    }

    design <- model.matrix(model_formula)


    if (!is.null(cov_var)) {
      colnames(design) <- c(levels(colData[, dependent]), covariates)
    } else {
      colnames(design) <- c(levels(colData[, dependent]))
    }

    perCombs <- split(
      t(combn(levels(colData[, dependent]), 2)),
      seq_len(nrow(t(combn(levels(colData[, dependent]), 2))))
    )


    expressions <- list()
    for (i in 1:length(perCombs)) {
      expressions[i] <- paste0(perCombs[[i]][2], "-", perCombs[[i]][1])
    }

    x <- unlist(expressions)

    contr.matrix <- limma::makeContrasts(
      contrasts = c(x, covariates),
      levels = design
    )

    # RNA
    d0 <- edgeR::DGEList(rna)
    d0 <- edgeR::calcNormFactors(d0)
    y <- limma::voom(d0, design)
    fit <- limma::lmFit(y, design)
    vfit <- limma::contrasts.fit(fit, contrasts = contr.matrix)
    efit <- limma::eBayes(vfit)

    df_rna <- list()
    for (i in 1:length(perCombs)) {
      df_rna[[i]] <- assign(paste0(
        "limma.results_",
        colnames(limma::topTable(efit))[i]
      ), limma::topTable(efit, coef = i, n = Inf))
    }

    names(df_rna) <- colnames(topTable(efit))[1:length(perCombs)]
    names(df_rna) <- gsub(
      pattern = ".", replacement = "vs",
      x = names(df_rna), fixed = TRUE
    )

    # PROTEIN
    fit <- limma::lmFit(protein, design, method = "robust")
    vfit <- limma::contrasts.fit(fit, contrasts = contr.matrix)
    efit <- limma::eBayes(vfit)
    df_protein <- list()
    for (i in 1:length(perCombs)) {
      df_protein[[i]] <- assign(paste0(
        "limma.results_",
        colnames(limma::topTable(efit))[i]
      ), limma::topTable(efit, coef = i, n = Inf))
    }

    names(df_protein) <- colnames(topTable(efit))[1:length(perCombs)]
    names(df_protein) <- gsub(
      pattern = ".", replacement = "vs",
      x = names(df_protein), fixed = TRUE
    )
  }

  ### NUMERIC DEPENDENT
  if (is.numeric(colData[, dependent])) {
    if (!is.na(cov_var)) {
      model_formula <- stats::as.formula(
        sprintf(
          "~%s + %s",
          dependent_var,
          cov_var
        )
      )
    }

    if (is.na(cov_var)) {
      model_formula <- stats::as.formula(
        sprintf(
          "~%s",
          dependent_var
        )
      )
    }


    design <- model.matrix(model_formula, data = colData)
    # RNA
    d0 <- edgeR::DGEList(rna)
    d0 <- edgeR::calcNormFactors(d0)
    y <- limma::voom(d0, design)
    fit <- limma::lmFit(y, design)
    efit <- limma::eBayes(fit)
    df_rna <- limma::topTable(efit,
      coef = paste(dependent),
      n = Inf, adjust = "BH"
    )

    # PROTEIN
    fit <- limma::lmFit(protein, design, method = "robust")
    efit <- limma::eBayes(fit)
    df_protein <- limma::topTable(efit,
      coef = paste(dependent),
      n = Inf, adjust = "BH"
    )
  }

  df_rna <- lapply(df_rna, function(x) {
    cbind(x, Identifier = rownames(x))
  })

  df_rna <- lapply(df_rna, format_res_limma,
    n_label = 20,
    gene_id_conversion = NULL,
    log2FoldChange = log2FoldChange
  )
  names(df_rna) <- gsub(
    pattern = "-", replacement = "vs",
    x = names(res), fixed = TRUE
  )

  df_protein <- lapply(df_protein, function(x) {
    cbind(x, Identifier = rownames(x))
  })
  gene_id_conversion <- as.data.frame(
    multiassay@ExperimentList@listData[["protein_raw"]]@elementMetadata@listData
  )

  if (is.null(gene_id_conversion$uniprot_id)) {
    gene_id_conversion <- NULL
  }

  df_protein <- lapply(df_protein, format_res_limma,
    n_label = 20,
    gene_id_conversion = gene_id_conversion,
    log2FoldChange = log2FoldChange
  )
  names(df_protein) <- gsub(
    pattern = "-", replacement = "vs",
    x = names(df_protein), fixed = TRUE
  )

  DE_list <- list(
    rna = df_rna,
    protein = df_protein
  )

  return(DE_list)
}
