#' Compute the module eigen value (PC1 of scaled transcriptomics/proteomics
#' expression) and correlates it to chosen covariates
#'
#' @param multiassay Multiassay experiment object generated by Omix
#' @param metadata metadata dataframe including chosen `covariates`
#' @param covariates clinical covariates
#' @param communities communities slot generated generated by
#' `communities_network`
#' @param filter_string_50 should be set to TRUE if `MOFA` integration was used
#'
#' @return a list object with `metadata_modules`, `corrplot`,`moduleTraitCor`,
#' `moduleTraitPvalue`,`moduleColors`,`moduleLabels`,`modules_eigen_value`
#'
#' @family Multi-omic integration downstream analysis
#'
#' @importFrom WGCNA moduleEigengenes orderMEs cor
#' @importFrom corrplot corrplot
#' @importFrom purrr map_dfr
#' @importFrom tibble enframe
#' @importFrom basetheme num2col
#' @export
#'

multiomics_modules <- function(multiassay,
                               metadata,
                               covariates,
                               communities,
                               filter_string_50=FALSE) {

  multimodal_omics <- multiassay@metadata$multimodal_object$omics
  df <- purrr::map_dfr(
    .x = communities,
    .f = ~ tibble::enframe(
      x = .x,
      name = NULL,
      value = "feature"
    ),
    .id = "community"
  )
  ## eigenvalue
  if(filter_string_50==TRUE){
  rownames(multimodal_omics$mRNA)=substr(rownames(multimodal_omics$mRNA),1,50)
  rownames(multimodal_omics$proteins)=substr(rownames(multimodal_omics$proteins),1,50)
  }

  rownames(multimodal_omics$mRNA) <- paste0(
    rownames(multimodal_omics$mRNA), "_rna")
  rownames(multimodal_omics$proteins) <- paste0(
    rownames(multimodal_omics$proteins), "_protein")

  matrix1 <- t(multimodal_omics$mRNA)
  matrix2 <- t(multimodal_omics$proteins)
  matrix <- cbind(matrix1, matrix2)

  df$color <- basetheme::num2col(as.numeric(df$community))
  moduleColors <- df$community
  names(moduleColors) <- df$feature

  # Recalculate MEs with color labels
  MEs0 <- WGCNA::moduleEigengenes(matrix[, df$feature],
                                  moduleColors)$eigengenes
  #MEs <- WGCNA::orderMEs(MEs0)
  MEs<-   MEs0
  moduleTraitCor <- WGCNA::cor(MEs, metadata[, c(covariates)], use = "p")
  MEs$id <- rownames(MEs)
  nSamples <- nrow(metadata)
  moduleTraitPvalue <- WGCNA::corPvalueStudent(moduleTraitCor, nSamples)
  metadata$id=  colnames(multimodal_omics$mRNA)

  metadata <- merge(metadata, MEs, by = "id")

  if(dim(moduleTraitCor)[1] >1){
  corrplot=corrplot::corrplot(t(moduleTraitCor[1:nrow(moduleTraitCor - 1), ]),
                              p.mat = t(moduleTraitPvalue),
                              insig = "label_sig",
                              sig.level = c(0.001, 0.01, 0.05),
                              diag = TRUE,
                              tl.cex=0.9,
                              pch.cex=2,
                              col = colorRampPalette(c("#2166AC","#4393C3","#92C5DE","#D1E5F0","#FDDBC7","#F4A582", "#D6604D","#B2182B"))(50))
  }else{
    corrplot=corrplot::corrplot(moduleTraitCor,
                                p.mat = moduleTraitPvalue,
                                insig = "label_sig",
                                sig.level = c(0.001, 0.01, 0.05),
                                diag = TRUE,
                                tl.cex=0.9,
                                pch.cex=2,
                                col = colorRampPalette(c("#2166AC","#4393C3","#92C5DE","#D1E5F0","#FDDBC7","#F4A582", "#D6604D","#B2182B"))(50))
    
  }
  

  return(list(
    metadata_modules = metadata,
    corrplot = corrplot,
    moduleTraitCor = moduleTraitCor,
    moduleTraitPvalue = moduleTraitPvalue,
    moduleColors = moduleColors,
    modulesLabels = df$feature,
    modules_eigen_value = MEs0
  ))
}

