#' Compute the module eigen value (PC1 of scaled transcriptomics/proteomics
#' expression) and correlates it to chosen covariates
#'
#' @param multiassay Multiassay experiment object generated by Omix
#' @param metadata metadata dataframe including chosen `covariates`
#' @param covariates clinical covariates
#' @param communities communities slot generated generated by
#' `communities_network`
#'
#' @return a list object with `metadata_modules`, `corrplot`,`moduleTraitCor`,
#' `moduleTraitPvalue`,`moduleColors`,`moduleLabels`,`modules_eigen_value`
#'
#' @family Multi-omic integration downstream analysis
#'
#' @importFrom WGCNA moduleEigengenes orderMEs cor
#' @importFrom corrplot corrplot
#' @importFrom purrr map_dfr
#' @importFrom tibble enframe
#' @importFrom basetheme num2col
#' @export
#'

multiomics_modules <- function(multiassay,
                               metadata,
                               covariates = c("pseudotime", "PHF1", "amyloid", "pTau"),
                               communities) {

  multimodal_omics <- multiassay@metadata$multimodal_object$omics
  df <- purrr::map_dfr(
    .x = communities,
    .f = ~ tibble::enframe(
      x = .x,
      name = NULL,
      value = "feature"
    ),
    .id = "community"
  )
  ## eigenvalue
  rownames(multimodal_omics$mRNA) <- paste0(
    rownames(multimodal_omics$mRNA), "_rna")
  rownames(multimodal_omics$proteins) <- paste0(
    rownames(multimodal_omics$proteins), "_protein")

  matrix1 <- t(multimodal_omics$mRNA)
  matrix2 <- t(multimodal_omics$proteins)
  matrix <- cbind(matrix1, matrix2)

  df$color <- basetheme::num2col(as.numeric(df$community))
  moduleColors <- df$community
  names(moduleColors) <- df$feature

  # Recalculate MEs with color labels
  MEs0 <- WGCNA::moduleEigengenes(scale(matrix[, df$feature]),
                                  moduleColors)$eigengenes
  MEs <- WGCNA::orderMEs(MEs0)

  moduleTraitCor <- WGCNA::cor(MEs, metadata[, c(covariates)], use = "p")
  MEs$sample_id <- rownames(MEs)
  nSamples <- nrow(metadata)
  moduleTraitPvalue <- WGCNA::corPvalueStudent(moduleTraitCor, nSamples)

  metadata <- merge(metadata, MEs, by = "sample_id")

  corrplot=corrplot::corrplot(t(moduleTraitCor[1:nrow(moduleTraitCor - 1), ]),
                              p.mat = t(moduleTraitPvalue),
                              insig = "label_sig",
                              sig.level = c(0.001, 0.01, 0.05),
                              diag = TRUE,
                              tl.cex=0.7,
                              pch.cex=0.5
  )

  return(list(
    metadata_modules = metadata,
    corrplot = corrplot,
    moduleTraitCor = moduleTraitCor,
    moduleTraitPvalue = moduleTraitPvalue,
    moduleColors = moduleColors,
    modulesLabels = df$feature,
    modules_eigen_value = MEs0
  ))
}

