#' Generate a report for single omic analysis
#'
#' @param multiassay Multiassay experiment object generated by Omix
#' @param integration_model Possible integration methods are `MOFA`,
#' `DIABLO`,`sMBPLS`,`iCluster`,`MEIFESTO`
#' @param report_folder_path report_folder_path folder path to save the report.
#' @param report_file  filename for report (without an extension).
#' @param database Enrichment database `GO_Molecular_Function_2021`,`GO_Cellular_Component_2021`,
#'  `GO_Biological_Process_2021`, `Reactome_2016` , `KEGG_2021_Human` , `MSigDB_Hallmark_2020`
#' @param cluster In the case of multi-omics clustering, choose two clusters of interest for differential analysis
#'
#' @family Report
#' @return Multi-omic analysis report html
#' @export
#'
multi_omic_report <- function(multiassay,
                               report_folder_path = getwd(),
                               report_file = "multi_omic_report_Omix",
                               integration_model='MOFA',
                               database='Reactome_2016',
                               cluster='C2-C1'){


  multiomic=multiassay@metadata[['integrative_results']][[integration_model]]
  multiomic$param$database=database
  multiomic$model=multiassay@metadata$integration[[integration_model]]
  multiomic$metadata=multiassay@metadata$multimodal_object$metadata
  multiomic$integration_param=multiassay@metadata[["parameters"]][["integration"]][[integration_model]]

  if(integration_model=='iCluster'){
  multiomic$param$cluster=cluster
  }

  report_file <- tools::file_path_sans_ext(report_file)

  cli::cli_h2("Generating report for integrative multi-omics analyses")


  metadata_tmp_path <- file.path(tempdir(), "metadata.qs")

  cli::cli_text("Writing temp files for report...")
  qs::qsave(
    multiomic,
    metadata_tmp_path
  )

  krd <- file.path(tempdir(), "krdqc")
  intd <- file.path(tempdir(), "idqc")
  dir.create(krd, showWarnings = FALSE)
  dir.create(intd, showWarnings = FALSE)

  cli::cli_text("Generating multi-omic analysis report...")

  if(  integration_model=='MOFA'){
  rmarkdown::render(
    system.file(
      "rmarkdown/templates/multi_omic/skeleton.Rmd",
      package = "Omix"
    ),
    params = list(
      metadata_path = metadata_tmp_path
    ),
    output_dir = report_folder_path,
    output_file = report_file,
    knit_root_dir = krd,
    intermediates_dir = intd,
    quiet = TRUE
  )
  }

  if(  integration_model=='DIABLO'){
    rmarkdown::render(
      system.file(
        "rmarkdown/templates/multi_omic/skeleton2.Rmd",
        package = "Omix"
      ),
      params = list(
        metadata_path = metadata_tmp_path
      ),
      output_dir = report_folder_path,
      output_file = report_file,
      knit_root_dir = krd,
      intermediates_dir = intd,
      quiet = TRUE
    )
  }

  if(  integration_model=='sMBPLS'){
    rmarkdown::render(
      system.file(
        "rmarkdown/templates/multi_omic/skeleton3.Rmd",
        package = "Omix"
      ),
      params = list(
        metadata_path = metadata_tmp_path
      ),
      output_dir = report_folder_path,
      output_file = report_file,
      knit_root_dir = krd,
      intermediates_dir = intd,
      quiet = TRUE
    )
  }

  if(  integration_model=='MBPLS'){
    rmarkdown::render(
      system.file(
        "rmarkdown/templates/multi_omic/skeleton4.Rmd",
        package = "Omix"
      ),
      params = list(
        metadata_path = metadata_tmp_path
      ),
      output_dir = report_folder_path,
      output_file = report_file,
      knit_root_dir = krd,
      intermediates_dir = intd,
      quiet = TRUE
    )
  }

  if( integration_model=='iCluster'){
    rmarkdown::render(
      system.file(
        "rmarkdown/templates/multi_omic/skeleton5.Rmd",
        package = "Omix"
      ),
      params = list(
        metadata_path = metadata_tmp_path
      ),
      output_dir = report_folder_path,
      output_file = report_file,
      knit_root_dir = krd,
      intermediates_dir = intd,
      quiet = TRUE
    )
  }

  report_file_name <- paste(report_file, ".html", sep = "")



}

