################################################################################
#' Process batch transcriptomics data
#'
#' @param multiassay Multiassay experiment object generated by Omix
#' `generate_multiassay`function
#' @param filter Logical whether to perform gene filtering
#' @param protein_coding Logical whether to filter out non protein coding genes
#' @param min_count Minimum count
#' @param min_sample Percentage of samples that have at least the `min_count`,
#' or else the gene is filtered out
#' @param dependent Dependent variable for the DeSEQ2 analysis, usually the
#' disease group variable
#' @param levels Character vector with reference group as first element.
#' Set parameter as NULL if dependent is NULL.
#' @param covariates Technical and biological covariates to use for
#' DESEQ2 analysis and denoising
#' @param batch_correction Logical whether to perform batch correction
#' @param batch Technical batch, use batch2 for another technical batch
#' @param remove_sample_outliers Logical whether to remove sample outliers
#'
#' @return a MultiAssayExperiment object with processed slots
#'
#' @importFrom MultiAssayExperiment MultiAssayExperiment listToMap colData
#'  getWithColData sampleMap
#' @importFrom SummarizedExperiment SummarizedExperiment
#' @importFrom DESeq2 DESeqDataSetFromMatrix counts
#' @importFrom stats prcomp
#' @importFrom magrittr set_names
#' @importFrom cli cli_alert_danger style_bold cli_alert_success
#' @importFrom limma removeBatchEffect
#'
#' @export

process_rna <- function(multiassay,
                        transformation = c("vst", "rlog", "log2"),
                        protein_coding,
                        filter,
                        min_count = 10,
                        min_sample = 1,
                        dependent,
                        levels = NULL,
                        covariates,
                        batch_correction,
                        batch,
                        remove_sample_outliers) {
  "%!in%" <- function(x, y) !("%in%"(x, y))
  suppressWarnings({
    rna_raw <- MultiAssayExperiment::getWithColData(
      multiassay,
      "rna_raw"
    )
  })

  colData <- data.frame(SummarizedExperiment::colData(rna_raw))

  if (!is.null(levels)) {
    colData[[dependent]] <- factor(colData[[dependent]], levels = levels)
  }

  if (!exists(batch)) {
    design_formula <- as.formula(paste("~", dependent, "+", paste(covariates,
      sep = " ",
      collapse = " + "
    )))
  } else {
    design_formula <- as.formula(paste("~", dependent, "+", paste(covariates,
      sep = " ",
      collapse = " + "
    ), "+ ", batch))
  }

  for (i in covariates) {
    rna_raw <- rna_raw[, !is.na(rna_raw[[paste(i)]])]
  }

  countData <- assays(rna_raw)[[1]]
  colData <- colData[colnames(countData), ]

  if (!all(colnames(countData) == rownames(colData))) {
    stop(cli::cli_alert_danger(
      paste("The columns in the", cli::style_bold("countData"),
        "should be same as the rows in", cli::style_bold("colData"),
        sep = " "
      )
    ))
  }

  dds <- DESeq2::DESeqDataSetFromMatrix(
    countData = countData,
    colData = colData,
    design = design_formula
  )

  dds <- DESeq2::estimateSizeFactors(dds)
  dim1 <- as.numeric(dim(dds)[1])

  cli::cli_alert_success("NORMALISATION & TRANSFORMATION")
  # matrix <- DESeq2::counts(dds, normalized=TRUE)

  if (transformation == "log2") {
    matrix <- data.frame(log2(counts(dds, normalized = TRUE) + 1))
  }

  if (transformation == "vst") {
    vsd <- DESeq2::vst(dds, blind = FALSE)
    matrix <- as.data.frame(assay(vsd))
  }

  if (transformation == "rlog") {
    rlog <- DESeq2::rlog(dds, blind = FALSE)
    matrix <- as.data.frame(assay(rlog))
  }

  if (filter == TRUE) {
    cli::cli_alert_success("GENE FILTERING")
    if (protein_coding == TRUE) {
      cli::cli_alert_success("Keeping only protein coding genes")
      protein_coding <- rowData(rna_raw)$gene_biotype == "protein_coding" &
        !is.na(rowData(rna_raw)$gene_biotype)
      dds <- dds[protein_coding, ]
      cli::cli_alert_success(paste(
        dim1 - sum(protein_coding),
        "/", dim1, "non protein coding genes were dropped"
      ))
      cli::cli_alert_success(paste(
        sum(protein_coding),
        "protein coding genes kept for analysis"
      ))
      dim1 <- as.numeric(dim(dds)[1])
    }
    cli::cli_alert_success(paste(
      "QC parameters selected require genes to have at least",
      (min_sample * 100), "% of samples with counts of", min_count, "or more"
    ))
    idx <- rowSums(DESeq2::counts(dds,
      normalized = TRUE
    ) >=
      min_count) >= dim(dds)[2] * min_sample

    keep <- as.numeric(sum(idx == TRUE))
    dds <- dds[idx, ]
    cli::cli_alert_success(paste(
      dim1 - keep,
      "/", dim1, "genes were dropped"
    ))

    cli::cli_alert_success(paste(keep, "genes kept for analysis"))

    if (transformation == "log2") {
      cli::cli_alert_success("LOG2 TRANSFORMATION")
      matrix <- data.frame(log2(counts(dds, normalized = TRUE) + 1))
    }

    if (transformation == "vst") {
      cli::cli_alert_success("VST TRANSFORMATION")
      vsd <- DESeq2::vst(dds, blind = FALSE)
      matrix <- as.data.frame(assay(vsd))
    }

    if (transformation == "rlog") {
      cli::cli_alert_success("RLOG TRANSFORMATION")
      rlog <- DESeq2::rlog(dds, blind = FALSE)
      matrix <- as.data.frame(assay(rlog))
    }
  }

  if (batch_correction == TRUE) {
    cli::cli_alert_success("BATCH CORRECTION")
    cli::cli_alert_success(paste(
      "Using Limma on", batch,
      "to remove technical artefacts, and",
      covariates, "as biological confounders"
    ))
    batch_data <- colData[batch]
    batch_data[[batch]] <- as.factor(batch_data[[batch]])

    covariates_data <- MultiAssayExperiment::colData(rna_raw)[, c(covariates)]
    covariates_data <- data.frame(covariates_data)

    matrix <- limma::removeBatchEffect(
      matrix,
      batch = batch_data[[batch]],
      covariates = covariates_data,
      design = model.matrix(~ colData[[dependent]],
        data = colData
      )
    )
  }

  if (remove_sample_outliers == TRUE) {
    dim2 <- dim(matrix)[2]
    cli::cli_alert_success("SAMPLE OUTLIERS REMOVAL")
    pca <- prcomp(t(matrix), scale. = FALSE, rank. = 1)
    U <- pca$x
    outliers <- rownames(apply(
      U, 2,
      function(x) {
        which(abs(x - mean(x)) >=
          (3 * sd(x)))
      }
    ))
    matrix <- matrix[, colnames(matrix) %!in% outliers]
    cli::cli_alert_success(paste(
      length(outliers), "sample outliers out of",
      dim2, " samples detected and dropped"
    ))
  }

  matrix <- as.data.frame(matrix)
  map <- MultiAssayExperiment::sampleMap(multiassay)
  map_df <- data.frame(map@listData)
  map_df <- map_df[which(map_df$assay == "rna_raw"), ]
  map_df <- map_df[match(
    colnames(matrix),
    map_df$colname
  ), ][c("primary", "colname")]
  map_df$assay <- "rna_processed"
  multiassay <- c(multiassay,
    rna_processed = matrix,
    sampleMap = map_df
  )


  metadata(multiassay)$dds <- dds

  if (remove_sample_outliers) {
    metadata(multiassay)$OutliersFlags$rna <- outliers
  }

  metadata(multiassay)$parameters_processing_rna <- list(
    min_count = min_count,
    min_sample = min_sample,
    dependent = dependent,
    levels = levels,
    covariates = covariates,
    filter = filter,
    batch_correction = batch_correction,
    batch = batch,
    remove_sample_outliers = remove_sample_outliers
  )
  cli::cli_alert_success("Transcriptomics data processed!")
  cli::cli_alert_success("Processing parameters saved in metadata")

  return(multiassay)
}


processed_rna <- function(multiassay,
                          custom_processed_df) {
  matrix <- as.data.frame(custom_processed_df)
  map <- MultiAssayExperiment::sampleMap(multiassay)
  map_df <- data.frame(map@listData)
  map_df <- map_df[which(map_df$assay == "rna_raw"), ]
  map_df <- map_df[match(
    colnames(matrix),
    map_df$colname
  ), ][c("primary", "colname")]
  map_df$assay <- "rna_processed"

  rm.rna_processed <- !grepl("rna_processed", names(experiments(multiassay)))
  multiassay <- multiassay[, , rm.rna_processed]
  multiassay <- c(multiassay,
    rna_processed = matrix,
    sampleMap = map_df
  )

  metadata(multiassay)$parameters_processing_rna$custom_processed_df <- TRUE

  cli::cli_alert_success("Custom processed transcriptomics added!")
}



#' Adds custom processed dataset to multiassay object
#'
#' @param multiassay
#' @param custom_processed_df
#'
#' @return
#' @export
#'
#' @examples
counts_rna <- function(multiassay,
                       custom_processed_df) {
  matrix <- as.data.frame(custom_processed_df)
  map <- MultiAssayExperiment::sampleMap(multiassay)
  map_df <- data.frame(map@listData)
  map_df <- map_df[which(map_df$assay == "rna_raw"), ]
  map_df <- map_df[match(
    colnames(matrix),
    map_df$colname
  ), ][c("primary", "colname")]
  map_df$assay <- "rna_counts"

  multiassay_temp <- c(multiassay,
    rna_counts = matrix,
    sampleMap = map_df
  )

  metadata(multiassay_temp)$parameters_processing_rna$counts_df <- TRUE
  return(multiassay_temp)

  cli::cli_alert_success("Raw transcriptomics counts added!")
}
