#' Performs single omic analysis of proteomic layer.
#'
#' @param multiassay Multiassay object generated by Omix
#' @param slot Default to "protein_processed"
#' @param dependent Dependent variable for the DeSEQ2 analysis, usually the
#' disease group variable
#' @param covariates Technical and biological covariates
#' @param levels Character vector with reference group as first element.
#' @param log2FoldChange Log2FC absolute threshold
#' @param padj adjusted p value threshold. Default to 0.05
#'
#' @return Adds differential expression results to Multiassay object generated by Omix
#' @importFrom MultiAssayExperiment MultiAssayExperiment listToMap colData
#' @importFrom SummarizedExperiment SummarizedExperiment colData
#' @importFrom stats as.formula
#' @import lme4
#' @importFrom limma makeContrasts lmFit contrasts.fit eBayes topTable
#' @import dplyr
#' @export
#'
protein_DE_analysis <- function(multiassay,
                                slot = "protein_processed",
                                dependent = "diagnosis",
                                covariates = NULL,
                                levels = c("Control", "AD"),
                                log2FoldChange = 0.5,
                                padj=0.5) {
  abundance <- multiassay@ExperimentList@listData[[paste(slot)]]

  if (("parameters_processing_protein" %in% names(multiassay@metadata)) == FALSE) {
    stop(cli::cli_alert_danger(
      paste("parameters_processing_protein not found in metadata, please run",
        cli::style_bold("process_protein"),
        sep = " "
      )
    ))
  }
  denoised <- multiassay@metadata$parameters_processing_protein$denoise
  cov <- multiassay@metadata$parameters_processing_protein$covariates


  if (isTRUE(denoised & isTRUE(cov == covariates))) {
    stop(cli::cli_alert_danger(
      paste("Processed protein data is already for designated covariates, model will be run for unadjusted covariates only")
    ))
    covariates <- setdiff(covariates, cov)
  }

  protein_raw <- MultiAssayExperiment::getWithColData(multiassay, i = "protein_raw", mode = "replace", verbose = F)
  colData <- data.frame(SummarizedExperiment::colData(protein_raw))
  colData <- colData %>% mutate(across(where(is.character), as.factor))

  if (!is.null(covariates)) {
    cov_var <- paste(covariates, collapse = " + ")

    if (any(is.na(colData[covariates]))) {
      stop(cli::cli_alert_danger(
        paste("Missing value in covariates, please use other covariates")
      ))
    }
  } else {
    cov_var <- NULL
  }

  dependent_var <- paste(dependent, collapse = " + ")

  if (!is.null(levels)) {
    colData[[dependent]] <- factor(colData[[dependent]], levels = levels)
  }

  for (i in colnames(colData)) {
    assign(i, colData[, i])
  }


  #### CATEGORICAL DEPENDENT VARIABLE

  if (!is.numeric(colData[, dependent])) {
    if (!is.null(cov_var)) {
      model_formula <- stats::as.formula(
        sprintf(
          "~0+ %s + %s",
          dependent_var,
          cov_var
        )
      )
    }
    if (is.null(cov_var)) {
      model_formula <- stats::as.formula(
        sprintf(
          "~0+ %s",
          dependent_var
        )
      )
    }

    design <- model.matrix(model_formula)


    if (!is.null(cov_var)) {
      colnames(design) <- c(levels(colData[, dependent]), covariates)
    } else {
      colnames(design) <- c(levels(colData[, dependent]))
    }

    perCombs <- split(
      t(combn(levels(colData[, dependent]), 2)),
      seq(nrow(t(combn(levels(colData[, dependent]), 2))))
    )


    expressions <- list()
    for (i in 1:length(perCombs)) {
      expressions[i] <- paste0(perCombs[[i]][2], "-", perCombs[[i]][1])
    }

    x <- unlist(expressions)

    contr.matrix <- limma::makeContrasts(contrasts = c(x, covariates), levels = colnames(design))

    fit <- limma::lmFit(abundance, design, method = "robust")
    vfit <- limma::contrasts.fit(fit, contrasts = contr.matrix)
    efit <- limma::eBayes(vfit, robust = TRUE)

    list_results <- list()

    for (i in 1:length(perCombs)) {
      list_results[[i]] <- assign(paste0(
        "limma.results_",
        colnames(limma::topTable(efit))[i]
      ), limma::topTable(efit, coef = i, n = Inf))
    }

    names(list_results) <- colnames(contr.matrix)[1:length(perCombs)]
  }

  #### NUMERIC DEPENDENT VARIABLE

  if (is.numeric(colData[, dependent])) {
    if (!is.null(cov_var)) {
      model_formula <- stats::as.formula(
        sprintf(
          "~%s + %s",
          dependent_var,
          cov_var
        )
      )
    }

    if (is.na(cov_var)) {
      model_formula <- stats::as.formula(
        sprintf(
          "~%s",
          dependent_var
        )
      )
    }


    design <- model.matrix(model_formula)
    fit <- lmFit(abundance, design, method = "robust")
    efit <- eBayes(fit, robust = TRUE)

    list_results <- list()
    for (i in 1:length(1)) {
      list_results[[i]] <- assign(
        paste0(
          "limma.results_",
          colnames(limma::topTable(efit))[i]
        ),
        limma::topTable(efit, coef = paste(dependent), adjust = "BH", number = Inf)
      )
    }

    names(list_results) <- paste(dependent)
  }

  list_results <- lapply(list_results, function(x) {
    cbind(x, Identifier = rownames(x))
  })
  gene_id_conversion <- as.data.frame(multiassay@ExperimentList@listData[["protein_raw"]]@elementMetadata@listData)

  if (is.null(gene_id_conversion$uniprot_id)) {
    gene_id_conversion <- NULL
  }

  res <- lapply(list_results, format_res_limma,
    n_label = 20,
    gene_id_conversion = gene_id_conversion,
    log2FoldChange = log2FoldChange
  )

  list_DEP_limma <- list()
  list_DEP_limma <- lapply(res, function(x) {
    up <- x$gene_name[which(x$padj <= 0.05 & x$de == "Up")]
    down <- x$gene_name[which(x$padj <= 0.05 & x$de == "Down")]
    return(list(
      up = up,
      down = down
    ))
  })

  res$plot <- lapply(res, volcano_plot_limma,
    log2FoldChange = log2FoldChange
  )
  res$sig_protein <- list_DEP_limma

  names(res) <- gsub(pattern = "-", replacement = "vs", x = names(res), fixed = TRUE)
  names(res$sig_protein) <- gsub(
    pattern = "-", replacement = "vs",
    x = names(res$sig_protein), fixed = TRUE
  )
  names(res$plot) <- gsub(
    pattern = "-", replacement = "vs",
    x = names(res$plot), fixed = TRUE
  )

  metadata(multiassay)$DEP <- res

  return(multiassay)
}
