#' Generate a report for single omic analysis
#'
#' @param multiassay Multiassay experiment object generated by Omix
#' @param report_folder_path report_folder_path folder path to save the report.
#' @param clinical_covariates clinical covariates
#' @param report_file  filename for report (without an extension).
#' @param dependent Dependent variable, usually the
#' disease group variable
#' @param map_by_column The common column name to link `metadata_rna`
#' and `metadata_protein` to the `individual_metadata`
#'
#' @family Report
#' @return QC report html
#' @export
#'
qc_report <- function(multiassay,
                              report_folder_path = getwd(),
                              report_file = "QC_report_Omix",
                              clinical_covariates=c("age","sex","diagnosis","Braak","amyloid"),
                              dependent='diagnosis',
                              map_by_column = 'sample_id'){

  qc=list()
  qc$metadata=data.frame(multiassay@colData)
  qc$dependent=dependent
  qc$map_by_column =map_by_column
  qc$data=multiassay@ExperimentList
  qc$clinical_covariates=clinical_covariates
  qc$param_rna=metadata(multiassay)$parameters$processing$rna
  qc$param_protein=metadata(multiassay)$parameters$processing$protein
  qc$processing_protein=metadata(multiassay)$parameters$processing_outputs$protein
  qc$processing_rna=metadata(multiassay)$parameters$processing_outputs$rna
  qc$multiomics=metadata(multiassay)$parameters$processing_outputs$multiomics

  report_file <- tools::file_path_sans_ext(report_file)

  cli::cli_h2("Generating report for quality control")


  metadata_tmp_path <- file.path(tempdir(), "metadata.qs")

  cli::cli_text("Writing temp files for report...")
  qs::qsave(
    qc,
    metadata_tmp_path
  )

  krd <- file.path(tempdir(), "krdqc")
  intd <- file.path(tempdir(), "idqc")
  dir.create(krd, showWarnings = FALSE)
  dir.create(intd, showWarnings = FALSE)

  cli::cli_text("Generating quality control report...")
  rmarkdown::render(
    system.file(
      "rmarkdown/templates/QC/skeleton.Rmd",
      package = "Omix"
    ),
    params = list(
      metadata_path = metadata_tmp_path
    ),
    output_dir = report_folder_path,
    output_file = report_file,
    knit_root_dir = krd,
    intermediates_dir = intd,
    quiet = TRUE
  )

  report_file_name <- paste(report_file, ".html", sep = "")

}

