#' Compare differential expressed genes and proteins
#'
#' @param multiassay Multiassay experiment object generated by Omix
#' @param slot If more than two comparison groups designates the slot name of 
#' interest in `names(multiassay@metadata$DEG)` and 
#' `names(multiassay@metadata$DEP)`
#'
#' @return
#' @export
#'
#' @examples
single_omic_comparison <- function(multiassay,
                                   slot = "LatevsControl") {

  if (("DEG" %in% names(multiassay@metadata)) == FALSE) {
    stop(cli::cli_alert_danger(
      paste("Differential experession results not present in metadata, please run",
        cli::style_bold("rna_DE_analysis"),
        sep = " "
      )
    ))
  }

  if (("DEP" %in% names(multiassay@metadata)) == FALSE) {
    stop(cli::cli_alert_danger(
      paste("Differential experession results not present in metadata, please run",
        cli::style_bold("protein_DE_analysis"),
        sep = " "
      )
    ))
  }

  DEG <- multiassay@metadata$DEG[[paste(slot)]]
  DEP <- multiassay@metadata$DEP[[paste(slot)]]


  t <- left_join(DEG, DEP, by = "gene_name")
  t$pvalue_category <- ifelse(t$padj.x <= 0.05 & t$padj.y <= 0.05, "double_platform",
    ifelse(t$padj.x <= 0.05 & t$padj.y > 0.05, "transcriptomics_only",
      ifelse(t$padj.x > 0.05 & t$padj.y <= 0.05, "proteomics_only", NA)
    )
  )

  t_new <- t[which(!is.na(t$pvalue_category)), ]

  t_dp <- t_new[t_new$pvalue_category == "double_platform", ]
  t_dp$direction <- ifelse(t_dp$log2FoldChange.x >= 0 & t_dp$log2FoldChange.y >= 0 |
    t_dp$log2FoldChange.x <= 0 & t_dp$log2FoldChange.y <= 0,
  "Concordant", "Discordant"
  )

  comparison_volcano <- ggpubr::ggscatter(t_dp,
    x = "log2FoldChange.x",
    y = "log2FoldChange.y", label = "gene_name",
    repel = TRUE, color = "direction",
    font.label = c(8, "plain")
  ) +
    xlab("log2FoldChange Transcriptome") +
    ylab("log2FoldChange Proteome") +
    geom_vline(
      xintercept = 0, linetype = "dotted",
      color = "grey", size = 1
    ) +
    geom_hline(
      yintercept = 0, linetype = "dotted",
      color = "grey", size = 1
    ) +
    theme(
      axis.text.x = element_text(face = "bold", size = 10),
      axis.text.y = element_text(face = "bold", size = 10),
      axis.text = element_text(size = 200)
    ) + theme_classic(base_size = 15)

  return(comparison_volcano)
}
