#' Performs sparse partial least squares regression on processed slots (rna and protein)
#'
#' @param multiassay Multiassay object generated by Omix
#' @param dependent Continuous dependent variable for sparse partial least squares
#' @return spls models for processed transcriptomics and proteomics
#' 
#'
#' @family Single-omic
#'
spls_wrapper <- function(multiassay,
                         dependent,
                         ncomp = 3,
                         test.keepX_rna = c(50,60,70,80,90,100),
                         test.keepX_protein = c(50,60,70,80,90,100)){
  
  args= list(multiassay=multiassay,
           slots = c(
             "rna_processed",
             "protein_processed"),
           intersect_genes = FALSE,
           ID_type = "gene_name")
  suppressMessages({
    multimodal <- do.call(get_multimodal_object, args)
  })
  multimodal_omics <- multimodal[[1]]
  
  metadata <- multimodal[[2]]
  Y <- metadata[[dependent]]
  
  Y=as.matrix(metadata[[dependent]])
  rownames(Y)=rownames(metadata)
  
  rownames(t(multimodal_omics$mRNA))==rownames(Y)
  
  datExpr1=t(multimodal_omics$mRNA)
  
  tune1=mixOmics::tune.spls(X=datExpr1, Y, ncomp = ncomp,
                 test.keepX =  test.keepX_rna,
                 validation = "Mfold", folds = 10, measure = "MSE", nrepeat = 3)
  
  tune.pls1 <- mixOmics::spls(X = datExpr1, Y = Y,keepX=tune1$choice.keepX, ncomp = ncomp, mode = 'regression')
  

  datExpr2=t(multimodal_omics$proteins)
  
  tune2=mixOmics::tune.spls(X=datExpr2, Y, ncomp = ncomp,
                            test.keepX =  test.keepX_protein,
                            validation = "Mfold", folds = 10, measure = "MSE", nrepeat = 3)
  
  tune.pls2 <- mixOmics::spls(X = datExpr2, Y = Y,keepX=tune2$choice.keepX, ncomp = ncomp, mode = 'regression')
  
  
  return(list(spls_rna=  tune.pls1,
              spls_protein=  tune.pls2))
}