#' Transcription factor target enrichment test
#'
#' @param communities communities slot generated generated by
#' `communities_network`
#' @param threshold Absolute threshold to filter weights
#' @param direction string indicating direction as "positive" or "negative"
#' @param TF_gmt GMT file with Transcription Factors and target genes. Check `https://maayanlab.cloud/chea3/`
#' @param weights Weight list generated by `extract_weights`
#'
#' @return TF target enrichment in each modules
#'
#' @family Multi-omic integration downstream analysis
#'
#' @importFrom ActivePathways read.GMT
#' @importFrom GeneOverlap drawHeatmap newGOM
#'
#' @export
#'
Transcription_Factor_enrichment <- function(communities,
                                            weights,
                                            TF_gmt = "Enrichr_Queries.gmt",
                                            threshold = 0.2,
                                            direction = "negative") {
  TF_genelist <- ActivePathways::read.GMT(TF_gmt)
  TF_genelist_list <- lapply(TF_genelist, function(x) {
    x$genes
  })

  if (direction == "negative") {
    TF_targets <- names(TF_genelist_list)[names(TF_genelist_list) %in% weights$weights_df$protein$Feature[which(weights$weights_df$protein$Weights <= -threshold)]]
  } else {
    TF_targets <- names(TF_genelist_list)[names(TF_genelist_list) %in% weights$weights_df$protein$Feature[which(weights$weights_df$protein$Weights >= threshold)]]
  }

  TF_focus <- intersect(names(TF_genelist_list), TF_targets)
  new <- TF_genelist_list[TF_focus]

  # filtering targets present in the RNA features
  new <- lapply(new, function(x) {
    x[which(x %in% weights$weights_df$rna$Feature)]
  })

  communities_rna <- lapply(communities, function(x) {
    x[grepl("_rna", x, fixed = TRUE)]
  })
  communities_rna <- lapply(communities_rna, function(x) {
    sub("\\_.*", "", x)
  })
  names(communities_rna) <- paste0("ME", names(communities_rna))
  gom.obj <- GeneOverlap::newGOM(communities_rna, new, genome.size = nrow(weights$weights_df$rna))

  return(gom.obj)
}
