################################################################################
#' Patient specific vertical integration
#'
#' @param multiassay Multiassay experiment object generated by Omix
#' @param slots Default are processed slots
#' @param integration Possible integration methods are `MOFA`,
#' `DIABLO`,`sMBPLS`,`iCluster`
#' @param intersect_genes Logical whether to keep intersecting features for
#' integration
#' @param dependent
#' @param map_by_column
#' @param design Design matrix (design = "full"): The strength of all
#' relationships between dataframes is maximised (= 1) – a “fully connected” design.
#' If design is set on cor, the correlation between PC1 of each dataset will be
#' set for the design matrix
#' @param ncomp Number of components in `DIABLO`,`sMBPLS`
#' @param range List of the range of numbers of features to keep in the tuning phase.
#' First element must be for rna, second for proteins
#'
#' @return Returns an integrated object in `multiassay@metadata$integration` to
#' be used for further analysis
#' @export
#'
#' @examples
vertical_integration <- function(multiassay,
                                 slots = c(
                                   "rna_processed",
                                   "protein_processed"
                                 ),
                                 integration = c("MOFA", "DIABLO", "sMBPLS"),
                                 intersect_genes = FALSE,
                                 ID_type = "gene_name",
                                 dependent = "Group",
                                 levels = c("Control", "Case"),
                                 design,
                                 ncomp = 2,
                                 range = list(
                                   mRNA = seq(5, 100, by = 10),
                                   proteins = seq(5, 100, by = 10)
                                 ),
                                 list.keepX = list(mRNA = c(50), proteins = c(50))) {
  multimodal_object <- .get_multimodal_object(
    multiassay,
    slots,
    intersect_genes,
    ID_type = ID_type
  )

  multimodal <- multimodal_object[[1]]
  metadata <- multimodal_object[[2]]

  Y <- metadata[[paste(dependent)]]

  if (integration == "DIABLO") {
    cli::cli_alert_success("VERTICAL INTEGRATION WITH DIABLO")
    Y <- factor(Y, levels = levels)
    int <- integrate_with_DIABLO(
      multimodal_omics = multimodal_omics,
      Y = Y,
      design = design,
      ncomp = ncomp,
      range = range
    )
  }

  if (integration == "sMBPLS") {
    cli::cli_alert_success("VERTICAL INTEGRATION WITH sMBPLS")
    Y <- as.matrix(Y)
    rownames(Y) <- rownames(metadata)
    int <- integrate_with_sMBPLS(
      multimodal_omics = multimodal_omics,
      Y = Y,
      design = design,
      ncomp = ncomp,
      list.keepX = list.keepX
    )
  }

  if (integration == "MOFA") {
    cli::cli_alert_success("VERTICAL INTEGRATION WITH MOFA")
    int <- integrate_with_MOFA(multimodal_omics)
  }

  multiassay@metadata$multimodal_object <- int[[1]]
  multiassay@metadata$integration[[paste(integration)]] <- int[[2]]
  print(int[[2]])

  return(multiassay)
}
