################################################################################
#' Patient specific vertical integration
#'
#' @param multiassay Multiassay experiment object generated by Omix
#' @param slots Default are processed slots
#' @param integration Possible integration methods are `MOFA`,
#' `DIABLO`,`sMBPLS`,`iCluster`,`MEIFESTO`
#' @param intersect_genes Logical whether to keep intersecting features for
#' integration
#' @param dependent
#' @param map_by_column
#' @param design Design matrix (design = "full"): The strength of all
#' relationships between dataframes is maximised (= 1) – a “fully connected” design.
#' If design is set on cor, the correlation between PC1 of each dataset will be
#' set for the design matrix
#' @param ncomp Number of components in `DIABLO`,`sMBPLS`
#' @param range List of the range of numbers of features to keep in the tuning phase.
#' First element must be for rna, second for proteins
#' @param try.N.clust number of cluster to tune in `iCluster`
#' @return Returns an integrated object in `multiassay@metadata$integration` to
#' be used for further analysis
#' @export
#'
#' @examples
vertical_integration <- function(multiassay,
                                 slots = c(
                                   "rna_processed",
                                   "protein_processed"
                                 ),
                                 integration = c("MOFA", "DIABLO", "sMBPLS",
                                                 "iCluster", "MEIFESTO"),
                                 intersect_genes = FALSE,
                                 ID_type = "gene_name",
                                 dependent = "Group",
                                 levels = c("Control", "Case"),
                                 design = c("cor", "full"),
                                 ncomp = 2,
                                 range = list(
                                   mRNA = seq(5, 100, by = 10),
                                   proteins = seq(5, 100, by = 10)
                                 ),
                                 list.keepX = list(mRNA = c(50), proteins = c(50)),
                                 num_factors = 10,
                                 time = "pseudotime",
                                 scale_views = TRUE,
                                 try.N.clust = 2:4,
                                 most_variable_feature = FALSE,...) {
  multiassay_arg=multiassay
  args <- list(
    multiassay = multiassay_arg,
    slots = slots,
    intersect_genes = intersect_genes,
    ID_type = ID_type
  )

  multimodal<- do.call('.get_multimodal_object', args)

  multimodal_omics <- multimodal[[1]]

  if (most_variable_feature == TRUE) {
    ### Keep only the most variable features in the high dimensional transcriptomics for modelling
    ### omics layers should be the same dimensions
    max_features <- dim(multimodal_omics[[2]])[1]
    keep <- order(apply(multimodal_omics[[1]], 1, var), decreasing = TRUE)[1:max_features]
    multimodal_omics[[1]] <- multimodal_omics[[1]][keep, ]

    cli::cli_alert_success(paste(max_features,'most variable features kept for analysis.'))
  }

  metadata <- multimodal[[2]]

  Y <- metadata[[paste(dependent)]]

  if (integration == "DIABLO") {
    cli::cli_alert_success("VERTICAL INTEGRATION WITH DIABLO")

    Y <- factor(Y, levels = levels)
    int <- integrate_with_DIABLO(
      multimodal_omics = multimodal_omics,
      Y = Y,
      design = design,
      ncomp = ncomp,
      range = range
    )
  }

  if (integration == "sMBPLS") {
    cli::cli_alert_success("VERTICAL INTEGRATION WITH sMBPLS")
    Y <- as.matrix(Y)
    rownames(Y) <- rownames(metadata)
    int <- integrate_with_sMBPLS(
      multimodal_omics = multimodal_omics,
      Y = Y,
      design = design,
      ncomp = ncomp,
      list.keepX = list.keepX
    )
  }

  if (integration == "MBPLS") {
    cli::cli_alert_success("VERTICAL INTEGRATION WITH MBPLS")
    Y <- as.matrix(Y)
    rownames(Y) <- rownames(metadata)
    int <- integrate_with_MBPLS(
      multimodal_omics = multimodal_omics,
      Y = Y,
      design = design,
      ncomp = ncomp
    )
  }


  if (integration == "MOFA") {
    cli::cli_alert_success("VERTICAL INTEGRATION WITH MOFA")
    int <- integrate_with_MOFA(multimodal_omics,
      num_factors = num_factors,
      scale_views = scale_views,
      metadata = metadata
    )
  }

  if (integration == "MEIFESTO") {
    cli::cli_alert_success("VERTICAL INTEGRATION WITH MEIFESTO")
    int <- integrate_with_MEIFESTO(multimodal_omics,
      num_factors = num_factors,
      scale_views = scale_views,
      metadata = metadata,
      time = time
    )
  }

  if (integration == "iCluster") {
    cli::cli_alert_success("VERTICAL INTEGRATION CLUSTERING WITH ICLUSTER")
    multimodal <- lapply(multimodal, data.frame)
    int <- integrate_with_iCluster(
      multimodal_omics = multimodal_omics,
      try.N.clust = try.N.clust
    )
  }

  multiassay@metadata$multimodal_object <- int[[1]]
  multiassay@metadata$integration[[paste(integration)]] <- int[[2]]

  return(multiassay)
}
